// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pingserver.proto

package knocking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KnockingClient is the client API for Knocking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnockingClient interface {
	KnockDB(ctx context.Context, in *RequestParam, opts ...grpc.CallOption) (*ResponseParam, error)
}

type knockingClient struct {
	cc grpc.ClientConnInterface
}

func NewKnockingClient(cc grpc.ClientConnInterface) KnockingClient {
	return &knockingClient{cc}
}

func (c *knockingClient) KnockDB(ctx context.Context, in *RequestParam, opts ...grpc.CallOption) (*ResponseParam, error) {
	out := new(ResponseParam)
	err := c.cc.Invoke(ctx, "/proto.Knocking/KnockDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnockingServer is the server API for Knocking service.
// All implementations must embed UnimplementedKnockingServer
// for forward compatibility
type KnockingServer interface {
	KnockDB(context.Context, *RequestParam) (*ResponseParam, error)
	mustEmbedUnimplementedKnockingServer()
}

// UnimplementedKnockingServer must be embedded to have forward compatible implementations.
type UnimplementedKnockingServer struct {
}

func (UnimplementedKnockingServer) KnockDB(context.Context, *RequestParam) (*ResponseParam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnockDB not implemented")
}
func (UnimplementedKnockingServer) mustEmbedUnimplementedKnockingServer() {}

// UnsafeKnockingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnockingServer will
// result in compilation errors.
type UnsafeKnockingServer interface {
	mustEmbedUnimplementedKnockingServer()
}

func RegisterKnockingServer(s grpc.ServiceRegistrar, srv KnockingServer) {
	s.RegisterService(&Knocking_ServiceDesc, srv)
}

func _Knocking_KnockDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnockingServer).KnockDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Knocking/KnockDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnockingServer).KnockDB(ctx, req.(*RequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

// Knocking_ServiceDesc is the grpc.ServiceDesc for Knocking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Knocking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Knocking",
	HandlerType: (*KnockingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KnockDB",
			Handler:    _Knocking_KnockDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pingserver.proto",
}
